title: "ViSNET AI Documentation"
author: "Sai Teja Devineni"
description: "v1.0"
permalink: /:title/
theme: jekyll-theme-yat
lang: "en"
excerpt_separator: "\n\n\n"
date_format: "%B %d, %Y"
show_downloads: "true"
